arcus/education_modules

- README.md
updating links in the README to data viz in ggplot2 module, since they were pointing to the old education-modules repo, not education_modules
> updating link to data viz in ggplot2 module

- README.md
- a_sample_module_template/a_sample_module_template.md
Updating the sample template as per our decisions last week (e.g. dropping the Contents section from overview), and also showing how to use YAML for short description, long description (is this module right for me? bit) and learning objectives. This means learning objectives don't need to be copy-pasted at the bottom of the module anymore, in the feedback section. Yay!
> Template update

- git_setup_windows/git_setup_windows.md
- setting_up_git_mac_and_linux/setting_up_git_mac_and_linux.md
They now have parallel titles, and the language about why we use `main` instead of `master` has been updated.
> Update setup modules

- bash_command_line_102/bash_command_line_102.md
In response to Issue https://github.com/arcus/education_modules/issues/166 , the quiz questions were not trimming extra whitespace before checking if the answer was correct. I believe this will fix that.
> trim whitespace from quiz input

- data_storage_models/data_storage_models.md
Tweaking wording in the cloud storage quiz (fixes #190), and combining local and network quizzes together (fixes #165, fixes #173). 
It was originally designed as two "parallel" quiz questions, with the same set of answers but first applying to local storage and later to network storage (and they had the same solution because the first was "which of these is true" and the second was "which of these is NOT true"). That wasn't working well because the repeated content was potentially confusing (user report #173 ), and because several of the answer options were not actually explained before the local storage quiz, only before the later network storage quiz (#165 ). I reorganized the content to make it one matrix quiz after the network storage section, rather than two separate multiple choice …
> Data storage models fix

- bash_command_line_101/bash_command_line_101.md
This addresses Issue https://github.com/arcus/education_modules/issues/213
The `man` command is not enabled in GitBash (and from the Git Bash conversation each time the issue is raised, is unlikely to every be available). This warning tells GitBash users that they can get the same info from an internet search.
I considered introducing `--help` here, but rejected it as it is far less helpful and has far less information than the manual, and the information provided is likely to be quite confusing for new users of Bash.
> add warning about no man in GitBash

- a_sample_module_template/a_sample_module_template.md
- assets/styles.css
- bash_103_combining_commands/bash_103_combining_commands.md
- bash_command_line_101/bash_command_line_101.md
- bash_command_line_102/bash_command_line_102.md
- bash_conditionals_loops/bash_conditionals_loops.md
- data_visualization_in_ggplot2/data_visualization_in_ggplot2.md
- data_visualization_in_open_source_software/data_visualization_in_open_source_software.md
- data_visualization_in_seaborn/data_visualization_in_seaborn.md
- git_creation_and_tracking/git_creation_and_tracking.md
- git_history_of_project/git_history_of_project.md
- git_intro/git_intro.md
- git_setup_mac_and_linux/git_setup_mac_and_linux.md
- git_setup_windows/git_setup_windows.md
- omics_orientation/omics_orientation.md
- pandas_transform/pandas_transform.md
- r_basics_transform_data/r_basics_transform_data.md
- r_missing_values/r_missing_values.md
- statistical_tests/statistical_tests.md
This is an update to the css file for all modules. It make several adjustments to highlight boxes:
- Adds new highlight boxes (e.g. `cool-fact`, `history`) 
- Replaces the icons before several kinds of highlight boxes
- Adds automatic text to the beginning of each highlight box
- Renames `learnmore` to `learn-more` for consistency with other multi-word divs
- Removes `hint` boxes, which we were not using
- Update from Font Awesome 5 to 6
In addition to the css file itself, this PR also includes changes to the module template. The section on highlight boxes was substantially updated both to add the new kinds of boxes available, as well as to clarify the purpose of existing highlight boxes:
- The instructions for when to use each kind of highlight box have been changed
- The examples for …
> Highlight box update

- reproducibility/reproducibility.md
(the link in the body of the module is correct, it just wasn't correct in the "mentioned in this module" section)
addresses issue #301
> fix broken link

- omics_orientation/omics_orientation.md
note reminding to update the REDCap link with the correct module name accidentally made it into the module
> remove reminder to change REDCap link

- database_normalization/database_normalization.md
links weren't working correctly in liascript, as the periods at the end of the URL text were being interpreted as _part of_ the URL.
Using the "raw" link instead of a descriptive link also goes against accessibility best practices -- addressed both of these with one change.
resolves issue #343
> Fix database normalization links

- assets/schemas/README.md
- assets/schemas/metadata_schema.json
- assets/schemas/stub-record.json
- assets/schemas/stub-record.yml
The `stub-record.yml` file just pulls the yml front matter from `bash_command_line_101.md`. `stub-record.yml` is now valid yml. 
This involved encapsulating the @ beginning keys with double quotes as well as those multi-line values. It also shoves `@end` into the double quote values. This is still not ideal but I wanted to push this into the example to serve as a start to work with. Getting closer!
> Remove education_module wrapper from schema, updates json stub-record; add yml stub-record

- docs.md
Add the `docs.md` file that will replace all the example text previously stored in templates. Yay!
Here it is rendered in lia, if you like: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/roseh_docs/docs.md
> Roseh docs

- docs.md
Adding some info about exercise modules, and a little of supporting info (in quizzes and content sections). I actually decided to have a separate exercise template to avoid confusion, even though it's super similar to the standard, but that change is in templates_update branch.
> Mll docs update

- _module_templates/macros_wrapper.md
Little fix in the print_list macro for wrapper modules. There was a little extra line of text to add our survey link, but it's not rendering properly and the survey link is available in the feedback section anyway, of course. So just taking that out.
> Remove text with survey link that's not rendering properly

- docs.md
- git_history_of_project/git_history_of_project.md
Fixes #393 
Also brings front matter up to date, replaces overview and feedback text with macros, and puts a gratitude box at the end of overview to be consistent with R basics series. 
Adds `git_basics` as an official sequence in docs.md
> Git history patch

- _module_templates/macros.md
make_survey_URL was assigning the version to fill a REDCap field that didn't exist, `version_number`. Updated to correctly set it to `version` which is the name of the field in REDCap.
this (hopefully) resolves #477
> fix make_survey_URL macro

- _module_templates/template_exercise.md
- _module_templates/template_standard.md
- _module_templates/template_wrapper.md
Fixes #517 
Note: We're not incrementing versions for templates, since those version fields are intended to be filled in for whatever module the author is using the template for. We might want to add a way to version templates, but for now they stay at 0.0.0
> Add missing front matter fields to templates

- .github/ISSUE_TEMPLATE/docs_update_checklist_v1.md
- .github/ISSUE_TEMPLATE/docs_update_checklist_v2.md
- _module_templates/template_standard.md
- _module_templates/template_wrapper.md
- docs.md
Updating docs, templates, and github issue to make `coding_required` a mandatory front matter field for all modules
Fixes #523
> Docs v2 update

- _module_templates/macros_bash.md
- bash_103_combining_commands/bash_103_combining_commands.md
- docs.md
This PR updates the front matter to docs v1, and also introduces a new macro for the bash_basics sequence lesson prep.
Line 60 in bash_command_line_103.md can be removed before merging, but doesn't have to be, it just links to the current location of the lesson prep macro.
> 537 docs v1 update bash combine commands

- sql_intermediate/sql_intermediate.md
This addresses 
- https://github.com/arcus/education_modules/issues/479 by restructuring a single sentence
- https://github.com/arcus/education_modules/issues/552 by adding the symbols for the buttons next to each time the button is referenced. Though the user referenced "question marks" in relation to hints, the check mark and light bulb symbols are the only ones present in the module so clarifying these should address this issue.
live link: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/sql-intermediate-clarifications/sql_intermediate/sql_intermediate.md#1
> Sql intermediate clarifications

- bash_103_combining_commands/bash_103_combining_commands.md
- bash_command_line_101/bash_command_line_101.md
This also includes a single metadata update to bash_103_combining commands that was omitted in its last update.
> Bash101 update to docs 2.0.0

- sql_joins/sql_joins.md
Note -- this SQL module uses its own small SQL databases different than those used in the SQL macro, so I'm leaving those in.  https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/sql-joins-fix/sql_joins/sql_joins.md#1 for final result.
> Fix typos, add metadata, fixes #610 #611 #588

- pandas_transform/pandas_transform.md
This fixes #348 by making sure that users don't need to type the complicated print command in themselves, they can just un-comment it.
> Add commented print command

- python_basics_lists_dictionaries/python_basics_lists_dictionaries.md
I added a line that strips all whitespace from the input (not just trimming at the beginning and end) and then matches it to an answer with no spaces. So regardless of what spaces a learner puts in, it will mark it correct. Note that if the learner puts in breaking spaces (e.g. `capital _ cities["Angola"]="Luanda"` or something like that), that will still be marked as correct here. I think that's probably okay though?
I also explicitly put in two different correct answers to match against, with an OR: One using double quotes and one using single quotes. So now it will be marked correct whether learners use double or single quotes. I didn't plan for a learner using both (`capital_cities['Angola']="Luanda"`) because that would be more complex and seemed unlikely, but we could totally put …
> Python basics: Lists and dicts update

- _module_templates/macros_genomics.md
- genomics_quality_control/genomics_quality_control.md
- genomics_setup/genomics_setup.md
I created a new macro to include after the overview section of any module using AWS for omics. Hopefully fixes #560 and fixes #620 although of course it would be much better if we had a reliable free option to offer folks. Until we find that, this explanation/apology is the best I could do. :(
So they're handy, here are the liascript links for the two affected modules: 
- [genomics setup](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/omics_aws_update/genomics_setup/genomics_setup.md)
- [genomics quality control](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/omics_aws_update/genomics_quality_control/genomics_quality_control.md)
NOTE: The import statements for the genomics macro file currently …
> Omics aws update

- bash_command_line_101/bash_command_line_101.md
This fixes https://github.com/arcus/education_modules/issues/657 and https://github.com/arcus/education_modules/issues/658
> Bash 101 typo and missing link

- bash_103_combining_commands/bash_103_combining_commands.md
- bash_scripts/bash_scripts.md
The "lab down skill up" webinar series of videos were all transitioned off of digitalrepository this June. There are new links available via tdnet: https://chop.tdnetdiscover.com/repositories/results?db=299&index=*&fct=Subjects%7Ecommand+line+and+computing+tools%7CSubjects%7Ecommand-line
But those videos are no longer publicly accessible, so we can't use that link in a module. I emailed LS about whether or not we can/should make those links public (the whole video series is possibly being sunsetted this year anyway), but in the meantime this PR removes the reference to those videos since they're inaccessible. Fixes #673 
Note: I searched our whole repo for links to resources on digitalrepository and these two modules were the only ones that came up so I don't think there are any other …
> Remove links to lab down skill up webinars by jacob levernier

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/user_reported.md
- CONTRIBUTING.md
Adding a `bug` issue template, primarily as a way for us to record some of the common problems and quick fixes we've learned about that are currently only stored in our collective memory. 
(As a reminder, the CONTRIBUTING doc will be automatically linked in a popup by GH whenever someone tries to create their first issue in the repo.)
> Issue template improvement

- regular_expressions_boundaries_anchors/regular_expressions_boundaries_anchors.md
Fixes #726 and also removes a little extra text that got inserted into the module accidentally
> Typo fixes for regex flags, boundaries, and anchors

- bash_103_combining_commands/bash_103_combining_commands.md
- bash_scripts/bash_scripts.md
Adding links to Jacob Levernier's bash webinars from the lab down skill up series, since we have the links for them on youtube now. Note that Jacob said he'd rather actually not be credited explicitly, so I didn't include his name.
> Add updated links to CLI videos from lab down skill up

- docs.md
This PR updates docs.md so that the "your frontmatter checklist" section correctly shows `collection` as required if both `data_task` and `data_domain` are unchecked; modules are required to have at least one of `collection`, `data_task`, or `data_domain`.
> Correct front matter checklist so collection is required if both data_task and data_domain are missing

- bash_command_line_102/bash_command_line_102.md
Fixes #759 
Also reordered metadata to be the standard order (as in docs.md), and removed a bunch of extra whitespace throughout. 
Added an import statement to get macros_bash and replaced the lesson prep text with the relevant macro.
> Stronger warning about `rm`, tidying up metadata

- .github/scripts/check_versions.sh
Fix problem of version incrementation check failing if the old version line and new version line do not appear in immediate sequence of one another in the git diff, as seen in #900, which is currently failing this check. 
adjust regex used to extract lines with version numbers from git diff to account for instances where there are other changed lines that appear in between the display of the old version line and the new version line. also minor variable renaming.
> fix version line regex

- .github/workflows/pull_metadata.yml
- .github/workflows/version_incrementation.yml
update download-artifact, upload-artifact, and checkout to use v4, to address deprecation of node.js 16 actions
> update marketplace actions to v4

- .github/ISSUE_TEMPLATE/qa-for-exercise-modules.md
- .github/ISSUE_TEMPLATE/qa-for-standard-modules.md
- .github/ISSUE_TEMPLATE/qa-for-wrapper-modules.md
resolves #922
Removes the link to nowhere for the "Directory Structure" heading
> remove directory structure link

- .github/scripts/public_list_of_modules.sh
- .github/workflows/pull_metadata.yml
This will make sure that all of the auto generated links on the DART website end in `.md#1` so they land on the overview page.
> End auto links with #1

- .github/workflows/link_check_cron.yml
periodically check for any links that no longer work in our module content. 
------
A few notes: 
Because there are files that always cause some failures (e.g., the intentionally bad urls being used as an example in a regex module), any errors found in a few files (how_to_troubleshoo.md, |macros.md, macros_python.md, and demystifying_regular_expressions.md) are excluded from the report that gets generated. This means this workflow will not catch any actually bad links in those modules. For a later iteration, we can always refine the code to not exclude those files all together, and instead just remove mentions of the links that we expected to fail, but this feels like a good skateboard. 
Also, while the cron syntax is valid, I'm not 100% sure it will accomplish what I actually want for it …
> add link check workflow

- regular_expressions_basics/regular_expressions_basics.md
Fixes broken regex 101 link in "Regular Expression Refresher" section (issue #937).
> Regex basics broken link

- bash_103_combining_commands/bash_103_combining_commands.md
- bash_command_line_101/bash_command_line_101.md
- bash_command_line_102/bash_command_line_102.md
- bash_conditionals_loops/bash_conditionals_loops.md
- bash_scripts/bash_scripts.md
This addresses the 5 Bash modules and gets them up to date with the latest standards for input and output blocks of code. Please note:
- This in a minor change in 4 of the modules, but only a revision in `bash_conditionals_loops` because that module contains no output code blocks. Modules containing output code blocks will now look noticeably different to learners, even if the content has not changed.
- Additional scaffolding was added to `bash_command_line_101` to clarify how the code blocks are being used, and describe the command prompt in a more useful way to learners who have never encountered it before.
- In some places, an additional code block was added to show that a file is being accessed using `cat` so that the contents of that file can be shown as output.
- While this …
> Styling bash code blocks in bash modules

- .github/ISSUE_TEMPLATE/docs_update_checklist_v5.md
- .github/ISSUE_TEMPLATE/qa-for-exercise-modules.md
- .github/ISSUE_TEMPLATE/qa-for-standard-modules.md
- .github/ISSUE_TEMPLATE/qa-for-wrapper-modules.md
- docs.md
data folder technically new to docs, but already in use. 
Also, changed `src` to `code` because `src` is not being used by anyone yet (mostly `notebooks` is in use, but that isn't well named for non-notebook files), so it will require the same amount of edits to bring up to standards either way, and `code` is more self-explanatory for learners who might poke around in our repo on their own to try to find materials. 
Made edits to the QA templates for now, though won't be long until we can deploy the action that looks for this, at which point we should be able to just remove that section from the manual QA process all together.
> update directory structure requirements

- demystifying_large_language_models/demystifying_large_language_models.md
Old (broken) cartoon in last box: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/demystifying_large_language_models/demystifying_large_language_models.md#8
New (fixed with help from Andre): https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/fix-cartoon/demystifying_large_language_models/demystifying_large_language_models.md#8
The new parser breaks nested markdown, Andre provided this fix, we might need to copy this approach elsewhere.  He writes:  
> One " was not closed, I added one after DeepAIHire ... I will have to fix this, the parser seems to be too greedy in this case, actually it should stop at the closing bracket ]. The quotes are translated into Unicode symbols, based on the language …
> Add fix for parser, changing internal markdown to html

- _module_templates/macros.md
Moved feedback link up to top of page, and also turned it into a button. 
I'm honestly not sure how I feel about it as a button, or if I think it would be better as just a link (which I implemented first, in [this commit](https://github.com/arcus/education_modules/commit/0116eac066f1ec00f3588b0576b3933decd9cbe7), screenshots below).
> Feedback macro
