- assets/styles.css
Hey Elizabeth, this one is a "trust me, please approve".  Let's see if you can figure out the approval situation!
> Improve inline code styling

- reproducibility/reproducibility.md
This was already approved, but I've updated the module to meet newer standards.  Can you just give this a quick one-over, @drelliche?   Not the full QA script, just flipping through to see if there's anything glaring. I'm seeing some old styles come through but I think it's just the Dreaded Caching....
Aside, we should think about what a "periodic update / improvement" QA looks like for already-approved modules.
> Joy update reproducibility

- demystifying_sql/demystifying_sql.md
Hi all!  @drelliche, @leemc-data-ed, @rosemm, @franzenr!
This is a **small**, 30-40 minute tops demystifying SQL module.  IDK if it really merits inclusion or not  and my feelings will NOT be hurt if we decide this is kind of orthogonal to what we've been doing so far and doesn't make sense to include.  
Take a gander at it.  NO images so it should be a super quick QA.  I don't have the bandwidth to make major changes so my ask is that you weigh in on whether it should be included with any minor sprucing up or if we should punt until we can get something more meaty.
Feel free to chat in comments, or self-select as a reviewer, depending on who has time!
> Demystifying sql

- statistical_tests/statistical_tests.md
Bring up to date with new module template; fix some broken links
> Check statistical tests in open source software module

- tidy_data/tidy_data.md
updated to remove ableist language
> quiz option wording update

- r_basics_transform_data/r_basics_transform_data.md
Solves #120 @rosemm I'm just yanking this through myself without approval like the chaos muppet I am
> Joy r typo fixes

- data_visualization_in_seaborn/data_visualization_in_seaborn.md
- python_basics_writing_python_code/python_basics_writing_python_code.md
- statistical_tests/statistical_tests.md
Replacing links to Intro to Python. 
Fixes #153 fixes #154 fixes #155
> Python link fix

- bash_command_line_102/bash_command_line_102.md
This should be a quick update after a conversation with Megan about difficulty finding the downloaded folders on a Windows machine. Once we decide this is appropriately clear, the language will be added to the other bash modules not yet on main.
> instructions for unzipping and opening learning_bash-main in cli

- data_visualization_in_open_source_software/data_visualization_in_open_source_software.md
Fixes several issues: #161 #162 and #146
> Data viz fix

- python_basics_writing_python_code/python_basics_writing_python_code.md
Minor updates, closes several issues:
#176: In the "Functions and methods" quiz on page 6 (line 227), the answer box discussed and answer that isn't one of the options. This has been fixed.
#195: Link to information about while loops was missing from page 11 (line 500); a resource has been added. 
#196: The code cells on page 15 had typos/errors in logic in the code that had them confusing. In the second cell, the third print statement is now print("This number is equal to or more than 100") (line 655). In the third cell, the code previously didn't account for all possibilities; new code has been added (lines 679-680).
> Python basics updates

- bash_command_line_101/bash_command_line_101.md
Fixes issue https://github.com/arcus/education_modules/issues/201
Updated the comment to make more sense to the target audience of this module, which is people who haven't really used bash before or want to start off at the very beginning.
> more informative comment for new Bash users

- reproducibility/reproducibility.md
> Joy fix link

- r_basics_introduction/r_basics_introduction.md
- r_basics_transform_data/r_basics_transform_data.md
> Add "Posit" info

- reproducibility/reproducibility.md
> Fix typo, adding one letter!

- git_intro/git_intro.md
> Joy yet another typo fix

- sql_intermediate/sql_intermediate.md
> Address #135 with Pete's suggestions

- bash_command_line_101/bash_command_line_101.md
fixing typos/formatting things noted in issue #220
> Bash 101 typos

- bash_command_line_101/bash_command_line_101.md
- demystifying_python/demystifying_python.md
- git_setup_mac_and_linux/git_setup_mac_and_linux.md
- git_setup_windows/git_setup_windows.md
This replaces all references to the program Atom with VS Code, addressing Issue https://github.com/arcus/education_modules/issues/237
> Atom sunsetting

- a_sample_module_template/a_sample_module_template.md
@franzenr @rosemm This should resolve https://github.com/arcus/education_modules/pull/241#issuecomment-1340013420
> module_version_number to 3.0.0

- python_basics_writing_python_code/python_basics_writing_python_code.md
Updated highlight boxes, version number, and module version number.
> Highlight box update

- omics_orientation/omics_orientation.md
Updated highlight box at line 57, version number, and module version number.
> Update highlight box

- citizen_science/citizen_science.md
New module on citizen science (the product of me losing power during the storm for 12 hours...). NIH strategic plan for data science emphasizes citizen science and public involvement, so seemed like good low hanging fruit.
> Citizen science

- quality_assurance_guide.md
This is to enhance the QA training process.
> add liascript info

- directories_and_file_paths/directories_and_file_paths.md
A teeny little PR. Just two small changes:
- fixed a typo I noticed while refreshing myself on the module content
- reworded a quiz question to take out the unnecessary introduction of the word "cohort", which is a technical term people may not be familiar with, and not at all needed for the question
> Small fixes for directories and file paths module

- tidy_data/tidy_data.md
bringing tidy data module up to code with template 3.0.0
> highlight box update for Tidy data

- git_creation_and_tracking/git_creation_and_tracking.md
- git_history_of_project/git_history_of_project.md
- git_intro/git_intro.md
- git_setup_mac_and_linux/git_setup_mac_and_linux.md
- git_setup_windows/git_setup_windows.md
5 modules were updated to have highlight boxes match the newest template.
git_intro
git_setup_mac_and_linux
git_setup_windows
git_creation_and_tracking
git_history_of_project
> Update highlight boxes in Git Modules

- geocode_lat_long/geocode_lat_long.md
Addresses insufficient scariness as mentioned in issue https://github.com/arcus/education_modules/issues/310
> make geocoding privacy warning scarier

- elements_of_maps/elements_of_maps.md
Was still linking to the branch, rather than to main.
> fix link to notebook that made maps

- bash_command_line_101/bash_command_line_101.md
@leemc-data-ed I added the `less` command in addition to `cat`. Please let me know if there is adequate information here to prep learners for eventually using `less` with omics stuff.
Other updates include a little revamp of the "manual" section and making the highlight boxes match the new formatting.
> add less command to bash 101

- demystifying_geospatial_data/demystifying_geospatial_data.md
- pandas_transform/pandas_transform.md
This updates highlight boxes in two modules:
- Demystifying geospatial data which had only one highlight box
- Transform Data with pandas which had a lot of highlight boxes and some additional formatting updates
> Highlight boxes and formatting update

- using_redcap_api/using_redcap_api.md
Fixes #279 
Please check my python solution in particular! I'm not sure environment variables are actually the most sensible approach here (although my googling around supports that). If there's a better way to do this, don't hesitate to suggest that.
> Redcap api add instructions for not pushing your API token to GH

- r_practice/r_practice.md
A few little things I noticed to fix while re-reviewing the R Practice module.
> R practice update

- geocode_lat_long/geocode_lat_long.md
This PR will close https://github.com/arcus/education_modules/issues/332
> Correct quiz question answers

- citizen_science/citizen_science.md
> fix misspelling of scientists

- bash_103_combining_commands/bash_103_combining_commands.md
This closes https://github.com/arcus/education_modules/issues/225
> correct incorrect descriptions of output

- demystifying_sql/demystifying_sql.md
- how_to_troubleshoot/how_to_troubleshoot.md
- r_basics_introduction/r_basics_introduction.md
- r_basics_transform_data/r_basics_transform_data.md
- r_basics_visualize_data/r_basics_visualize_data.md
- statistical_tests/statistical_tests.md
This PR has updated the highlight boxes to the new version in the following modules:
- How to Troubleshoot
- R Basics: Intro
- R Basics: Transforming Data with deployer
- R Basics: Visualizing Data with ggplot2
- Demystifying SQL
- Statistical Tests
No other changes have been made to these modules.
> Highlight box updates - multiple modules

- assets/schemas/metadata_schema.json
- assets/schemas/pull_metadata.sh
- assets/schemas/stub-record.yml
- bash_103_combining_commands/bash_103_combining_commands.md
- bash_command_line_101/bash_command_line_101.md
- bash_command_line_102/bash_command_line_102.md
- bash_conditionals_loops/bash_conditionals_loops.md
- bash_scripts/bash_scripts.md
- citizen_science/citizen_science.md
- data_management_basics/data_management_basics.md
- data_visualization_in_open_source_software/data_visualization_in_open_source_software.md
- data_visualization_in_seaborn/data_visualization_in_seaborn.md
- database_normalization/database_normalization.md
- git_creation_and_tracking/git_creation_and_tracking.md
- git_history_of_project/git_history_of_project.md
- git_setup_mac_and_linux/git_setup_mac_and_linux.md
- git_setup_windows/git_setup_windows.md
- pandas_transform/pandas_transform.md
- python_practice/python_practice.md
- reproducibility/reproducibility.md
- sql_basics/sql_basics.md
- sql_intermediate/sql_intermediate.md
- sql_joins/sql_joins.md
- statistical_tests/statistical_tests.md
- tidy_data/tidy_data.md
This is a first attempt at encoding the metadata as macros in the LiaScript front matter.  21 modules (the [Green pathway from wave 1](https://github.com/arcus/DART_wave1_analysis/blob/main/reports/notebooks/proposed_pathways.md#green-pathway-955-min) have had metadata added to them.
> Metatdata as macros

- docs.md
Here's it rendered in lia: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/docs_update_metdata/docs.md#7
> Updating front matter fields and descriptions in docs.md to coordinate with metadata

- r_basics_visualize_data/r_basics_visualize_data.md
Just changing a couple of small metadata things.
> Joy update r basics viz

- r_reshape_long_wide/r_reshape_long_wide.md
Updating highlight boxes (fixes #429), and adding a care box to fix #353.
Also bringing up to date with docs v1, including updating front matter, replacing text with macros, and adding version history.
Also see https://github.com/arcus/education_r_environment/pull/21
> R reshape update

- data_visualization_in_ggplot2/data_visualization_in_ggplot2.md
- data_visualization_in_seaborn/data_visualization_in_seaborn.md
Fixes #428 
Updates highlight boxes, and brings up to date with docs v1 (front matter updated, macros replace text, removed link to another module in additional resources)
> Seaborn update

- data_visualization_in_open_source_software/data_visualization_in_open_source_software.md
Fixes #427 (update highlight boxes)
Also brings module up to date with docs v1, including updating front matter, replacing text with macros, and removing links to our modules from additional resources section.
> Data viz oss update

- citizen_science/citizen_science.md
- demystifying_geospatial_data/demystifying_geospatial_data.md
Fixes #406 
Brings up to date with docs v1, including updating front matter, doing version history, and replacing text with macros
> Update to demystifying geospatial data

- citizen_science/citizen_science.md
Brings up to date with docs v1, fixes #407 
here's the [lia link](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/rmh_little_fixes/citizen_science/citizen_science.md), so you have that handy. Other than the updates to front matter, it's just one tiny typo fix.
> Update to citizen science

- reproducibility/reproducibility.md
Fixes #349 and brings module up to metadata standards.  See it in situ at https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/joy-improve-reproducibility/reproducibility/reproducibility.md#1
> Improve Reproducibility

- sql_intermediate/sql_intermediate.md
Fixes several issues: #134, #183, #357, #437, and adds new metadata and macro standards.  See it in situ at https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/joy-improve-sql-intermediate/sql_intermediate/sql_intermediate.md#1
> Joy improve sql intermediate

- bash_conditionals_loops/bash_conditionals_loops.md
This is a typo-fixing/trust fall PR to correct errors in a quiz.
> turn digits into written out words

- git_intro/git_intro.md
@rosemm tell me what you think... I added a new learning objective, 5 minutes of time, and a quiz question in addition to the material.  Check it out here: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/joy-improve-intro-git/git_intro/git_intro.md#1.  This will fix #425 425
> Add Git v GitHub info to Intro to Version Control

- _module_templates/macros_regex.md
- demystifying_regular_expressions/demystifying_regular_expressions.md
- regular_expressions_basics/regular_expressions_basics.md
- regular_expressions_boundaries_anchors/regular_expressions_boundaries_anchors.md
- regular_expressions_groups/regular_expressions_groups.md
- regular_expressions_lookaheads/regular_expressions_lookaheads.md
The import line will need to be updated before merging, but right now it links to the macro in this PR so that you can see what the warning looks like.
> Warning box about putting data in regex101

- intro_to_nhst/intro_to_nhst.md
Here's the lia link, so you've got that handy: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/intro_to_nhst/intro_to_nhst/intro_to_nhst.md#1
> Intro to nhst

- python_basics_variables_functions_methods/python_basics_variables_functions_methods.md
Minor fixes! I don't think we really need to increment the version number, since I highly doubt anyone has seen this yet.
> Changed title and minor front matter update

- .github/ISSUE_TEMPLATE/docs_update_checklist_v1.md
- docs.md
Fixes #462 
Fixes #463 
Fixes #464
> Docs patch

- data_visualization_in_seaborn/data_visualization_in_seaborn.md
Not ideal, but maybe will work for now? No pressure if not, I think we'll be okay if this doesn't make it in right now.
> Add instructions for installing packages

- demystifying_python/demystifying_python.md
- docs.md
- statistical_tests/statistical_tests.md
update python basics links to first module in the new 4 part series
> fix outdated python basics links

- data_visualization_in_ggplot2/data_visualization_in_ggplot2.md
- regular_expressions_lookaheads/regular_expressions_lookaheads.md
* fix links to boundaries + anchors regex module within lookaheads module
* fix link to data viz in OSS in ggplot2 module
> Fix incorrect links

- demystifying_regular_expressions/demystifying_regular_expressions.md
> remove comma from link

- demystifying_large_language_models/demystifying_large_language_models.md
Link now takes you to specific section of article as intended 
resolves #549
> fix Science link

- intro_to_nhst/intro_to_nhst.md
We had a few feedback records mention typos in Intro to NHST (#556), this PR corrects those and a few others I found.
> Correct typos

- data_management_basics/data_management_basics.md
Fixes #589, #604, and #605 .  This fixes the mermaid chart not showing up (liascript has to update its way of working with mermaid and hasn't done so yet, so we have to deprecate mermaid to the last version that still works with liascript).  It also gets this module up to version 1 of docs (#604) and then version 2 of docs (#605 )
See https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/fix-mermaid/data_management_basics/data_management_basics.md#4 in which the diagram now appears.
> fix mermaid changes that liascript hasn't picked up yet

- demystifying_sql/demystifying_sql.md
This fixes issue #505 , which asks for more explanation of relational data, and also #607 and #608, which have to do with updating metadata.
> Joy demyst sql fix

- r_basics_introduction/r_basics_introduction.md
> Add missing answer

- .github/scripts/process_metadata.sh
- bash_103_combining_commands/bash_103_combining_commands.md
- docs.md
There was a typo in reproduced in three places. This PR fixes that.
> replace depends_on_knowledge_in with depends_on_knowledge_availabe_in

- sql_intermediate/sql_intermediate.md
Simple fix of typo, adding bullets to version hx, and upversioning metadata standard and module
> Fix #627, typo and metadata version update

- learning_to_learn/learning_to_learn.md
Fixes #591 
Fixes #494 
Also brings module up to date with docs v2: fixes #635 fixes #636
> Learning to learn update

- reproducibility/reproducibility.md
Clarify that excel does support scripts, but it's still worthwhile to learn R or Python
Fixes #483 
Also adds link to a syllabus of academic readings in social science, fixes #480 (Note that it includes repeated use of the word "fuck" though! Note sure if we want to avoid this link for that reason. But it is truly a really excellent list of academic readings, and actually ended up being the basis for a real class I took in graduate school from Prof Srivastava.)
> Updates to reproducibility

- r_basics_visualize_data/r_basics_visualize_data.md
Add troubleshooting box about how to get plots to show up in the plots pane rather than inline, fixes #531 
Typo, fixes #530 
Revise to remove double negative, fixes #511 
Add help box for color vs fill aesthetic mapping, fixes #594
> R Basics ggplot2 update

- r_summary_stats/r_summary_stats.md
> Roseh typos

- data_visualization_in_seaborn/data_visualization_in_seaborn.md
Was missing  module_type. Fixes #654
> Add missing front matter field

- data_storage_models/data_storage_models.md
Note that the title of this module (in the metadata) has been changed to match the internal title of the module, "Types of Data Storage Models"
All connected feedback in the quick module feedback in REDCap has already been edited to reflect this change.
> Update data storage solutions docsv2

- r_basics_transform_data/r_basics_transform_data.md
> R transform fixing little typos

- r_practice/r_practice.md
> R practice update to docs v2

- omics_orientation/omics_orientation.md
Fixes #690 
Fixes #691 
Also fixes #548 (minor issue with headings)
> Omics orientation update to docs v2

- data_visualization_in_seaborn/data_visualization_in_seaborn.md
- statistical_tests/statistical_tests.md
Bring up to date with docs v2
Fixes #699 
Fixes #700 
Note that I corrected the heading structure for additional resources, which then required fixing a link in the seaborn module, which is why that file got touched.  
Also:
Fixes #701 adding new content to additional resources
> Statistical tests update to docs v2

- genomics_setup/genomics_setup.md
> Genomics setup fix

- tidy_data/tidy_data.md
Updated for compliance with docs v1 and v2.
> Tidy data docs update

- using_redcap_api/using_redcap_api.md
> Update redcap api module to docs v1 and v2

- bash_103_combining_commands/bash_103_combining_commands.md
Closed a parenthesis to fix link.
> Fixed previous version link

- gh_issues_analysis.Rmd
Just a little script, for anyone that would like to be able to look at information about our GH issues in a more systematic way.
> Add r script for analyzing GH issues

- bash_scripts/bash_scripts.md
Fixes https://github.com/arcus/education_modules/issues/756 and fixes https://github.com/arcus/education_modules/issues/735
> Clarify instructions, correct typo

- docker_101/docker_101.md
Clarifying description and prereqs to make it clearer that this isn't a beginner module. Also added a new help box about creating files with no extension (like a Dockerfile). 
Fixes #575 
Fixes #616
> Docker101 update

- data_visualization_in_ggplot2/data_visualization_in_ggplot2.md
> Fix broken link, fixes #714

- _module_templates/macros_sql.md
- sql_basics/sql_basics.md
> Joy bug squashing

- bash_command_line_101/bash_command_line_101.md
- bash_conditionals_loops/bash_conditionals_loops.md
- demystifying_containers/demystifying_containers.md
- demystifying_large_language_models/demystifying_large_language_models.md
This fixes 4 typos:
fixes #734 
fixes #727 
fixes #723 
fixes #569
> typo squashing

- tidy_data/tidy_data.md
peerj link periodically gave users issues, so changed to a new link. Also included an HTML version for accessibility options. Finally, edited sentence to give credit to both authors, not just Broman.
resolves #653
> update link to Broman and Woo paper

- python_basics_exercise/python_basics_exercise.md
Highlighted a hint for looping through dictionaries to make the content stand out. Merging will close #684.
> Added highlight box for hint

- directories_and_file_paths/directories_and_file_paths.md
resolves #779
resolves #780
resolves #781
brings this module up to alignment with v1-3 of docs
> update to docs v3

- docs.md
> edit learn_to_code description

- how_to_troubleshoot/how_to_troubleshoot.md
resolves #776
resolves #777 
resolves #778 
changed the `collection` from learn_to_code to intro_to_data_science based upon my interpretation of the descriptions of the collections in [docs](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/docs.md#38)
verification from @drelliche on my interpretation would be useful :)
> How to troubleshoot docs update

- r_basics_practice/r_basics_practice.md
This is intended as a fourth module in the R Basics sequence. Fixes #641 Fixes #746
It follows almost exactly the same steps and tasks as the Intro, Viz, and Transform modules, but on a real dataset. I tried not to introduce any new commands, and it includes significantly more scaffolding than the existing R Practice module (basically, it has pseudocode instructions for each task). My hope is that this will provide an opportunity to consolidate learning from the Basics sequence before moving onto more complicated R content.
Related PR in the environment repo: https://github.com/arcus/education_r_environment/pull/27 
P.S. I also think there could be some value in this module as a "homework" assignment to offer folks at the end of an R 101 workshop, as an opportunity for them to practice!
> R Basics Practice module

- r_basics_introduction/r_basics_introduction.md
Fixes #807 
Here's a link right to the new section, so you have it handy: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/add-new-chunks/r_basics_introduction/r_basics_introduction.md#11 
Also brings up to date with docs v3:
Fixes #808 
Fixes #809
> R Basics Intro: Add new subsection explaining how to add code chunks

- demystifying_geospatial_data/demystifying_geospatial_data.md
improve link a11y and address link that no longer was routing to correct content.
resolves #550
resolves #822
> improve link a11y

- r_basics_visualize_data/r_basics_visualize_data.md
> Fix quiz that was displaying incorrectly

- demystifying_machine_learning/demystifying_machine_learning.md
> Adding more resources

- reproducibility/reproducibility.md
Fixes #833 
Also corrected some little issues in the metadata. This module is now up to date with docs v3.
> Add learn-more box linking to demystifying containers

- r_basics_transform_data/r_basics_transform_data.md
quiz question about pipes can accept either pipe, whitespace optional
closes #749
> pipe quiz flexibility

- r_basics_transform_data/r_basics_transform_data.md
closes #831 
couldn't figure out how to make back references work (possibly not supported in liascript?) so it's a little ugly, but it works!!
> filter quiz update

- data_management_basics/data_management_basics.md
> Added stronger language about publisher responsibilities

- _module_templates/macros_python.md
- data_visualization_in_seaborn/data_visualization_in_seaborn.md
- pandas_transform/pandas_transform.md
- python_basics_lists_dictionaries/python_basics_lists_dictionaries.md
- python_basics_loops_conditionals/python_basics_loops_conditionals.md
- python_basics_variables_functions_methods/python_basics_variables_functions_methods.md
These changes replace SageMath Cells in Python coding modules, implementing Pyodide instead.
> Implement Pyodide in Python coding modules

- sql_basics/sql_basics.md
- sql_intermediate/sql_intermediate.md
- sql_joins/sql_joins.md
resolves #865
resolves #866
resolves #867
> link a11y fixes

- sql_joins/sql_joins.md
Updated the data types in SQL Joins (which doesn't use `macros_sql.md`.
> Sql joins alasql updates

- statistical_tests/statistical_tests.md
> Remove prereqs for R and Python since this module doesn't actually require coding

- bash_103_combining_commands/bash_103_combining_commands.md
- bash_command_line_101/bash_command_line_101.md
- bash_command_line_102/bash_command_line_102.md
- bash_conditionals_loops/bash_conditionals_loops.md
- bash_scripts/bash_scripts.md
- demystifying_python/demystifying_python.md
- docker_101/docker_101.md
- genomics_quality_control/genomics_quality_control.md
- genomics_setup/genomics_setup.md
- git_creation_and_tracking/git_creation_and_tracking.md
- git_history_of_project/git_history_of_project.md
- git_setup_mac_and_linux/git_setup_mac_and_linux.md
- git_setup_windows/git_setup_windows.md
Added Demystifying the Command Line Interface to a bunch of module metadata as a pre req and/or in "depends on knowledge available in" list. Would close #890.
> Git and bash metadata updates

- _module_templates/macros.md
This is what this will cause to change: a new paragraph after "Overview" and new paragraph at the end of "Feedback". See screenshots below!
> Joy add link

- generalized_linear_regression/generalized_linear_regression.md
This is a reordering of sections and renaming of section headers after a conversation.
> Reorder generalized linear regression

- demystifying_command_line/demystifying_command_line.md
- sql_basics/sql_basics.md
- sql_intermediate/sql_intermediate.md
- sql_joins/sql_joins.md
This PR fixes three issues: #868, #889, #904
> Joy issue squashing

- docs.md
remove instructions for reconstructing version history, as we have completed that initiative.
> Remove version reconstruction

- .github/ISSUE_TEMPLATE/qa-for-exercise-modules.md
- .github/ISSUE_TEMPLATE/qa-for-standard-modules.md
- .github/ISSUE_TEMPLATE/qa-for-wrapper-modules.md
- _for_authors/inclusivity_guidelines.md
- _for_authors/write_a_module.md
- _module_templates/macros_genomics.md
- bias_variance_tradeoff/bias_variance_tradeoff.md
- citizen_science/citizen_science.md
- data_visualization_in_ggplot2/data_visualization_in_ggplot2.md
- data_visualization_in_seaborn/data_visualization_in_seaborn.md
- demystifying_machine_learning/demystifying_machine_learning.md
- docker_101/docker_101.md
- docs.md
- docs/index.md
- elements_of_maps/elements_of_maps.md
- generalized_linear_regression/generalized_linear_regression.md
- genomics_quality_control/genomics_quality_control.md
- genomics_setup/genomics_setup.md
- git_creation_and_tracking/git_creation_and_tracking.md
- python_practice/python_practice.md
- r_basics_introduction/r_basics_introduction.md
- r_basics_visualize_data/r_basics_visualize_data.md
- r_missing_values/r_missing_values.md
- regular_expressions_lookaheads/regular_expressions_lookaheads.md
- using_redcap_api/using_redcap_api.md
Fixing broken links in a variety of files. 
Resolves #941 (aside from any that were not able to be reproduced, commented on the issue).
> Link fixing

- _module_templates/macros.md
wrapping tags so they don't get parsed as plain text
> wrap overview div tags with lia-keep to preserve them from bad parsing
